name: bluehive_exam
description: Blue Hive flutter exam - Castel.


# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# Version number
version: 1.0.0+1


environment:
  sdk: ">=2.16.2 <3.0.0"


# Dependencies
dependencies:
  # object comparison
  equatable: ^2.0.3
  # routing
  auto_route: ^3.2.4
  # default
  cupertino_icons: ^1.0.2
  # bottom sheet
  modal_bottom_sheet: ^2.0.1
  # number picker widget
  numberpicker: ^2.1.1
  # bloc state management
  flutter_bloc: ^8.0.1
  # firebase core
  firebase_core: ^1.15.0
  # noSql database
  cloud_firestore: ^3.1.13
  # 3rd party authentication - firebase
  firebase_auth: ^3.3.15
  # google auth
  google_sign_in: ^5.3.0
  # form validation
  form_field_validator: ^1.1.0
  # firebase storage
  firebase_storage: ^10.2.14
  # date time parser
  intl: ^0.17.0
  flutter:
    sdk: flutter


dev_dependencies:
  # required by code generators
  build_runner: ^2.1.8
  # routing code generator
  auto_route_generator: ^3.2.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
